#ifndef CPU_HPP
#define CPU_HPP

#include <cstdint>
#include <string>
#include <unordered_map>
#include "../interrupt_manager.hpp"
#include "../mmu.hpp"
#include "register.hpp"
#include "opcode.hpp"

/* Central Processing Unit 
 * Executes instructions, manages registers, handles flags, and coordinates 
 * interactions with the InterruptManager and Mmu. */
class Cpu {
public:
    Cpu(InterruptManager* interrupt_manager, Mmu* mmu);

    void reset();
    void tick();

    std::string representation() const;

private:
    Register reg;
    InterruptManager* interrupt_manager;
    Mmu* mmu;

    // Cpu states
    enum class State {FETCH, WORK, INTERRUPT, HALT, STOP};
    void set_state(State new_state);

    // Main loop variables
    uint8_t locked;
    State state;
    bool cb_prefix;
    Opcode* opcode;
    uint8_t current_m_cycles;
    bool interrupt_enable_scheduled;
    InterruptType interrupt_type;

    // Cycle methods for each state
    void fetch_cycle();
    void work_cycle();
    void interrupt_cycle();

    // Opcode dictionaries
    std::unordered_map<uint8_t, Opcode*> opcodes;
    std::unordered_map<uint8_t, Opcode*> cb_opcodes;

    void initialise_opcodes_dictionaries();

    // Variables for the opcodes to manipulate
    uint8_t z8;
    uint16_t z16;
    bool early_exit;

    // Basis of cpu functionality
    void add(uint8_t value);
    void add_with_carry(uint8_t value);
    void subtract(uint8_t value);
    void subtract_with_carry(uint8_t value);
    void and_(uint8_t value);
    void or_(uint8_t value);
    void xor_(uint8_t value);
    void compare(uint8_t value);
    uint8_t increment(uint8_t value);
    uint8_t decrement(uint8_t value);
    void add_hl(uint16_t value);
    uint16_t add_signed8(uint16_t value16, int8_t value8);
    uint8_t swap(uint8_t value);
    void decimal_adjust_accumulator();
    void complement_accumulator();
    void complement_carry_flag();
    void set_carry_flag();
    uint8_t rotate_left_circular(uint8_t value);
    uint8_t rotate_left(uint8_t value);
    uint8_t rotate_right_circular(uint8_t value);
    uint8_t rotate_right(uint8_t value);
    uint8_t shift_left_arithmetic(uint8_t value);
    uint8_t shift_right_arithmetic(uint8_t value);
    uint8_t shift_right_logical(uint8_t value);
    void bit(uint8_t value, int position);
    uint8_t set(uint8_t value, int position);
    uint8_t reset(uint8_t value, int position);

    // Opcode generators
    Opcode opcode_0x00_generator();
    Opcode opcode_0x01_generator();
    Opcode opcode_0x02_generator();
    Opcode opcode_0x03_generator();
    Opcode opcode_0x04_generator();
    Opcode opcode_0x05_generator();
    Opcode opcode_0x06_generator();
    Opcode opcode_0x07_generator();
    Opcode opcode_0x08_generator();
    Opcode opcode_0x09_generator();
    Opcode opcode_0x0a_generator();
    Opcode opcode_0x0b_generator();
    Opcode opcode_0x0c_generator();
    Opcode opcode_0x0d_generator();
    Opcode opcode_0x0e_generator();
    Opcode opcode_0x0f_generator();
    Opcode opcode_0x10_generator();
    Opcode opcode_0x11_generator();
    Opcode opcode_0x12_generator();
    Opcode opcode_0x13_generator();
    Opcode opcode_0x14_generator();
    Opcode opcode_0x15_generator();
    Opcode opcode_0x16_generator();
    Opcode opcode_0x17_generator();
    Opcode opcode_0x18_generator();
    Opcode opcode_0x19_generator();
    Opcode opcode_0x1a_generator();
    Opcode opcode_0x1b_generator();
    Opcode opcode_0x1c_generator();
    Opcode opcode_0x1d_generator();
    Opcode opcode_0x1e_generator();
    Opcode opcode_0x1f_generator();
    Opcode opcode_0x20_generator();
    Opcode opcode_0x21_generator();
    Opcode opcode_0x22_generator();
    Opcode opcode_0x23_generator();
    Opcode opcode_0x24_generator();
    Opcode opcode_0x25_generator();
    Opcode opcode_0x26_generator();
    Opcode opcode_0x27_generator();
    Opcode opcode_0x28_generator();
    Opcode opcode_0x29_generator();
    Opcode opcode_0x2a_generator();
    Opcode opcode_0x2b_generator();
    Opcode opcode_0x2c_generator();
    Opcode opcode_0x2d_generator();
    Opcode opcode_0x2e_generator();
    Opcode opcode_0x2f_generator();
    Opcode opcode_0x30_generator();
    Opcode opcode_0x31_generator();
    Opcode opcode_0x32_generator();
    Opcode opcode_0x33_generator();
    Opcode opcode_0x34_generator();
    Opcode opcode_0x35_generator();
    Opcode opcode_0x36_generator();
    Opcode opcode_0x37_generator();
    Opcode opcode_0x38_generator();
    Opcode opcode_0x39_generator();
    Opcode opcode_0x3a_generator();
    Opcode opcode_0x3b_generator();
    Opcode opcode_0x3c_generator();
    Opcode opcode_0x3d_generator();
    Opcode opcode_0x3e_generator();
    Opcode opcode_0x3f_generator();
    Opcode opcode_0x40_generator();
    Opcode opcode_0x41_generator();
    Opcode opcode_0x42_generator();
    Opcode opcode_0x43_generator();
    Opcode opcode_0x44_generator();
    Opcode opcode_0x45_generator();
    Opcode opcode_0x46_generator();
    Opcode opcode_0x47_generator();
    Opcode opcode_0x48_generator();
    Opcode opcode_0x49_generator();
    Opcode opcode_0x4a_generator();
    Opcode opcode_0x4b_generator();
    Opcode opcode_0x4c_generator();
    Opcode opcode_0x4d_generator();
    Opcode opcode_0x4e_generator();
    Opcode opcode_0x4f_generator();
    Opcode opcode_0x50_generator();
    Opcode opcode_0x51_generator();
    Opcode opcode_0x52_generator();
    Opcode opcode_0x53_generator();
    Opcode opcode_0x54_generator();
    Opcode opcode_0x55_generator();
    Opcode opcode_0x56_generator();
    Opcode opcode_0x57_generator();
    Opcode opcode_0x58_generator();
    Opcode opcode_0x59_generator();
    Opcode opcode_0x5a_generator();
    Opcode opcode_0x5b_generator();
    Opcode opcode_0x5c_generator();
    Opcode opcode_0x5d_generator();
    Opcode opcode_0x5e_generator();
    Opcode opcode_0x5f_generator();
    Opcode opcode_0x60_generator();
    Opcode opcode_0x61_generator();
    Opcode opcode_0x62_generator();
    Opcode opcode_0x63_generator();
    Opcode opcode_0x64_generator();
    Opcode opcode_0x65_generator();
    Opcode opcode_0x66_generator();
    Opcode opcode_0x67_generator();
    Opcode opcode_0x68_generator();
    Opcode opcode_0x69_generator();
    Opcode opcode_0x6a_generator();
    Opcode opcode_0x6b_generator();
    Opcode opcode_0x6c_generator();
    Opcode opcode_0x6d_generator();
    Opcode opcode_0x6e_generator();
    Opcode opcode_0x6f_generator();
    Opcode opcode_0x70_generator();
    Opcode opcode_0x71_generator();
    Opcode opcode_0x72_generator();
    Opcode opcode_0x73_generator();
    Opcode opcode_0x74_generator();
    Opcode opcode_0x75_generator();
    Opcode opcode_0x76_generator();
    Opcode opcode_0x77_generator();
    Opcode opcode_0x78_generator();
    Opcode opcode_0x79_generator();
    Opcode opcode_0x7a_generator();
    Opcode opcode_0x7b_generator();
    Opcode opcode_0x7c_generator();
    Opcode opcode_0x7d_generator();
    Opcode opcode_0x7e_generator();
    Opcode opcode_0x7f_generator();
    Opcode opcode_0x80_generator();
    Opcode opcode_0x81_generator();
    Opcode opcode_0x82_generator();
    Opcode opcode_0x83_generator();
    Opcode opcode_0x84_generator();
    Opcode opcode_0x85_generator();
    Opcode opcode_0x86_generator();
    Opcode opcode_0x87_generator();
    Opcode opcode_0x88_generator();
    Opcode opcode_0x89_generator();
    Opcode opcode_0x8a_generator();
    Opcode opcode_0x8b_generator();
    Opcode opcode_0x8c_generator();
    Opcode opcode_0x8d_generator();
    Opcode opcode_0x8e_generator();
    Opcode opcode_0x8f_generator();
    Opcode opcode_0x90_generator();
    Opcode opcode_0x91_generator();
    Opcode opcode_0x92_generator();
    Opcode opcode_0x93_generator();
    Opcode opcode_0x94_generator();
    Opcode opcode_0x95_generator();
    Opcode opcode_0x96_generator();
    Opcode opcode_0x97_generator();
    Opcode opcode_0x98_generator();
    Opcode opcode_0x99_generator();
    Opcode opcode_0x9a_generator();
    Opcode opcode_0x9b_generator();
    Opcode opcode_0x9c_generator();
    Opcode opcode_0x9d_generator();
    Opcode opcode_0x9e_generator();
    Opcode opcode_0x9f_generator();
    Opcode opcode_0xa0_generator();
    Opcode opcode_0xa1_generator();
    Opcode opcode_0xa2_generator();
    Opcode opcode_0xa3_generator();
    Opcode opcode_0xa4_generator();
    Opcode opcode_0xa5_generator();
    Opcode opcode_0xa6_generator();
    Opcode opcode_0xa7_generator();
    Opcode opcode_0xa8_generator();
    Opcode opcode_0xa9_generator();
    Opcode opcode_0xaa_generator();
    Opcode opcode_0xab_generator();
    Opcode opcode_0xac_generator();
    Opcode opcode_0xad_generator();
    Opcode opcode_0xae_generator();
    Opcode opcode_0xaf_generator();
    Opcode opcode_0xb0_generator();
    Opcode opcode_0xb1_generator();
    Opcode opcode_0xb2_generator();
    Opcode opcode_0xb3_generator();
    Opcode opcode_0xb4_generator();
    Opcode opcode_0xb5_generator();
    Opcode opcode_0xb6_generator();
    Opcode opcode_0xb7_generator();
    Opcode opcode_0xb8_generator();
    Opcode opcode_0xb9_generator();
    Opcode opcode_0xba_generator();
    Opcode opcode_0xbb_generator();
    Opcode opcode_0xbc_generator();
    Opcode opcode_0xbd_generator();
    Opcode opcode_0xbe_generator();
    Opcode opcode_0xbf_generator();
    Opcode opcode_0xc0_generator();
    Opcode opcode_0xc1_generator();
    Opcode opcode_0xc2_generator();
    Opcode opcode_0xc3_generator();
    Opcode opcode_0xc4_generator();
    Opcode opcode_0xc5_generator();
    Opcode opcode_0xc6_generator();
    Opcode opcode_0xc7_generator();
    Opcode opcode_0xc8_generator();
    Opcode opcode_0xc9_generator();
    Opcode opcode_0xca_generator();
    Opcode opcode_0xcb_generator();
    Opcode opcode_0xcc_generator();
    Opcode opcode_0xcd_generator();
    Opcode opcode_0xce_generator();
    Opcode opcode_0xcf_generator();
    Opcode opcode_0xd0_generator();
    Opcode opcode_0xd1_generator();
    Opcode opcode_0xd2_generator();
    Opcode opcode_0xd4_generator();
    Opcode opcode_0xd5_generator();
    Opcode opcode_0xd6_generator();
    Opcode opcode_0xd7_generator();
    Opcode opcode_0xd8_generator();
    Opcode opcode_0xd9_generator();
    Opcode opcode_0xda_generator();
    Opcode opcode_0xdc_generator();
    Opcode opcode_0xde_generator();
    Opcode opcode_0xdf_generator();
    Opcode opcode_0xe0_generator();
    Opcode opcode_0xe1_generator();
    Opcode opcode_0xe2_generator();
    Opcode opcode_0xe5_generator();
    Opcode opcode_0xe6_generator();
    Opcode opcode_0xe7_generator();
    Opcode opcode_0xe8_generator();
    Opcode opcode_0xe9_generator();
    Opcode opcode_0xea_generator();
    Opcode opcode_0xee_generator();
    Opcode opcode_0xef_generator();
    Opcode opcode_0xf0_generator();
    Opcode opcode_0xf1_generator();
    Opcode opcode_0xf2_generator();
    Opcode opcode_0xf3_generator();
    Opcode opcode_0xf5_generator();
    Opcode opcode_0xf6_generator();
    Opcode opcode_0xf7_generator();
    Opcode opcode_0xf8_generator();
    Opcode opcode_0xf9_generator();
    Opcode opcode_0xfa_generator();
    Opcode opcode_0xfb_generator();
    Opcode opcode_0xfe_generator();
    Opcode opcode_0xff_generator();

    // CB opcode generators 
    Opcode opcode_cb_0x00_generator();
    Opcode opcode_cb_0x01_generator();
    Opcode opcode_cb_0x02_generator();
    Opcode opcode_cb_0x03_generator();
    Opcode opcode_cb_0x04_generator();
    Opcode opcode_cb_0x05_generator();
    Opcode opcode_cb_0x06_generator();
    Opcode opcode_cb_0x07_generator();
    Opcode opcode_cb_0x08_generator();
    Opcode opcode_cb_0x09_generator();
    Opcode opcode_cb_0x0a_generator();
    Opcode opcode_cb_0x0b_generator();
    Opcode opcode_cb_0x0c_generator();
    Opcode opcode_cb_0x0d_generator();
    Opcode opcode_cb_0x0e_generator();
    Opcode opcode_cb_0x0f_generator();
    Opcode opcode_cb_0x10_generator();
    Opcode opcode_cb_0x11_generator();
    Opcode opcode_cb_0x12_generator();
    Opcode opcode_cb_0x13_generator();
    Opcode opcode_cb_0x14_generator();
    Opcode opcode_cb_0x15_generator();
    Opcode opcode_cb_0x16_generator();
    Opcode opcode_cb_0x17_generator();
    Opcode opcode_cb_0x18_generator();
    Opcode opcode_cb_0x19_generator();
    Opcode opcode_cb_0x1a_generator();
    Opcode opcode_cb_0x1b_generator();
    Opcode opcode_cb_0x1c_generator();
    Opcode opcode_cb_0x1d_generator();
    Opcode opcode_cb_0x1e_generator();
    Opcode opcode_cb_0x1f_generator();
    Opcode opcode_cb_0x20_generator();
    Opcode opcode_cb_0x21_generator();
    Opcode opcode_cb_0x22_generator();
    Opcode opcode_cb_0x23_generator();
    Opcode opcode_cb_0x24_generator();
    Opcode opcode_cb_0x25_generator();
    Opcode opcode_cb_0x26_generator();
    Opcode opcode_cb_0x27_generator();
    Opcode opcode_cb_0x28_generator();
    Opcode opcode_cb_0x29_generator();
    Opcode opcode_cb_0x2a_generator();
    Opcode opcode_cb_0x2b_generator();
    Opcode opcode_cb_0x2c_generator();
    Opcode opcode_cb_0x2d_generator();
    Opcode opcode_cb_0x2e_generator();
    Opcode opcode_cb_0x2f_generator();
    Opcode opcode_cb_0x30_generator();
    Opcode opcode_cb_0x31_generator();
    Opcode opcode_cb_0x32_generator();
    Opcode opcode_cb_0x33_generator();
    Opcode opcode_cb_0x34_generator();
    Opcode opcode_cb_0x35_generator();
    Opcode opcode_cb_0x36_generator();
    Opcode opcode_cb_0x37_generator();
    Opcode opcode_cb_0x38_generator();
    Opcode opcode_cb_0x39_generator();
    Opcode opcode_cb_0x3a_generator();
    Opcode opcode_cb_0x3b_generator();
    Opcode opcode_cb_0x3c_generator();
    Opcode opcode_cb_0x3d_generator();
    Opcode opcode_cb_0x3e_generator();
    Opcode opcode_cb_0x3f_generator();
    Opcode opcode_cb_0x40_generator();
    Opcode opcode_cb_0x41_generator();
    Opcode opcode_cb_0x42_generator();
    Opcode opcode_cb_0x43_generator();
    Opcode opcode_cb_0x44_generator();
    Opcode opcode_cb_0x45_generator();
    Opcode opcode_cb_0x46_generator();
    Opcode opcode_cb_0x47_generator();
    Opcode opcode_cb_0x48_generator();
    Opcode opcode_cb_0x49_generator();
    Opcode opcode_cb_0x4a_generator();
    Opcode opcode_cb_0x4b_generator();
    Opcode opcode_cb_0x4c_generator();
    Opcode opcode_cb_0x4d_generator();
    Opcode opcode_cb_0x4e_generator();
    Opcode opcode_cb_0x4f_generator();
    Opcode opcode_cb_0x50_generator();
    Opcode opcode_cb_0x51_generator();
    Opcode opcode_cb_0x52_generator();
    Opcode opcode_cb_0x53_generator();
    Opcode opcode_cb_0x54_generator();
    Opcode opcode_cb_0x55_generator();
    Opcode opcode_cb_0x56_generator();
    Opcode opcode_cb_0x57_generator();
    Opcode opcode_cb_0x58_generator();
    Opcode opcode_cb_0x59_generator();
    Opcode opcode_cb_0x5a_generator();
    Opcode opcode_cb_0x5b_generator();
    Opcode opcode_cb_0x5c_generator();
    Opcode opcode_cb_0x5d_generator();
    Opcode opcode_cb_0x5e_generator();
    Opcode opcode_cb_0x5f_generator();
    Opcode opcode_cb_0x60_generator();
    Opcode opcode_cb_0x61_generator();
    Opcode opcode_cb_0x62_generator();
    Opcode opcode_cb_0x63_generator();
    Opcode opcode_cb_0x64_generator();
    Opcode opcode_cb_0x65_generator();
    Opcode opcode_cb_0x66_generator();
    Opcode opcode_cb_0x67_generator();
    Opcode opcode_cb_0x68_generator();
    Opcode opcode_cb_0x69_generator();
    Opcode opcode_cb_0x6a_generator();
    Opcode opcode_cb_0x6b_generator();
    Opcode opcode_cb_0x6c_generator();
    Opcode opcode_cb_0x6d_generator();
    Opcode opcode_cb_0x6e_generator();
    Opcode opcode_cb_0x6f_generator();
    Opcode opcode_cb_0x70_generator();
    Opcode opcode_cb_0x71_generator();
    Opcode opcode_cb_0x72_generator();
    Opcode opcode_cb_0x73_generator();
    Opcode opcode_cb_0x74_generator();
    Opcode opcode_cb_0x75_generator();
    Opcode opcode_cb_0x76_generator();
    Opcode opcode_cb_0x77_generator();
    Opcode opcode_cb_0x78_generator();
    Opcode opcode_cb_0x79_generator();
    Opcode opcode_cb_0x7a_generator();
    Opcode opcode_cb_0x7b_generator();
    Opcode opcode_cb_0x7c_generator();
    Opcode opcode_cb_0x7d_generator();
    Opcode opcode_cb_0x7e_generator();
    Opcode opcode_cb_0x7f_generator();
    Opcode opcode_cb_0x80_generator();
    Opcode opcode_cb_0x81_generator();
    Opcode opcode_cb_0x82_generator();
    Opcode opcode_cb_0x83_generator();
    Opcode opcode_cb_0x84_generator();
    Opcode opcode_cb_0x85_generator();
    Opcode opcode_cb_0x86_generator();
    Opcode opcode_cb_0x87_generator();
    Opcode opcode_cb_0x88_generator();
    Opcode opcode_cb_0x89_generator();
    Opcode opcode_cb_0x8a_generator();
    Opcode opcode_cb_0x8b_generator();
    Opcode opcode_cb_0x8c_generator();
    Opcode opcode_cb_0x8d_generator();
    Opcode opcode_cb_0x8e_generator();
    Opcode opcode_cb_0x8f_generator();
    Opcode opcode_cb_0x90_generator();
    Opcode opcode_cb_0x91_generator();
    Opcode opcode_cb_0x92_generator();
    Opcode opcode_cb_0x93_generator();
    Opcode opcode_cb_0x94_generator();
    Opcode opcode_cb_0x95_generator();
    Opcode opcode_cb_0x96_generator();
    Opcode opcode_cb_0x97_generator();
    Opcode opcode_cb_0x98_generator();
    Opcode opcode_cb_0x99_generator();
    Opcode opcode_cb_0x9a_generator();
    Opcode opcode_cb_0x9b_generator();
    Opcode opcode_cb_0x9c_generator();
    Opcode opcode_cb_0x9d_generator();
    Opcode opcode_cb_0x9e_generator();
    Opcode opcode_cb_0x9f_generator();
    Opcode opcode_cb_0xa0_generator();
    Opcode opcode_cb_0xa1_generator();
    Opcode opcode_cb_0xa2_generator();
    Opcode opcode_cb_0xa3_generator();
    Opcode opcode_cb_0xa4_generator();
    Opcode opcode_cb_0xa5_generator();
    Opcode opcode_cb_0xa6_generator();
    Opcode opcode_cb_0xa7_generator();
    Opcode opcode_cb_0xa8_generator();
    Opcode opcode_cb_0xa9_generator();
    Opcode opcode_cb_0xaa_generator();
    Opcode opcode_cb_0xab_generator();
    Opcode opcode_cb_0xac_generator();
    Opcode opcode_cb_0xad_generator();
    Opcode opcode_cb_0xae_generator();
    Opcode opcode_cb_0xaf_generator();
    Opcode opcode_cb_0xb0_generator();
    Opcode opcode_cb_0xb1_generator();
    Opcode opcode_cb_0xb2_generator();
    Opcode opcode_cb_0xb3_generator();
    Opcode opcode_cb_0xb4_generator();
    Opcode opcode_cb_0xb5_generator();
    Opcode opcode_cb_0xb6_generator();
    Opcode opcode_cb_0xb7_generator();
    Opcode opcode_cb_0xb8_generator();
    Opcode opcode_cb_0xb9_generator();
    Opcode opcode_cb_0xba_generator();
    Opcode opcode_cb_0xbb_generator();
    Opcode opcode_cb_0xbc_generator();
    Opcode opcode_cb_0xbd_generator();
    Opcode opcode_cb_0xbe_generator();
    Opcode opcode_cb_0xbf_generator();
    Opcode opcode_cb_0xc0_generator();
    Opcode opcode_cb_0xc1_generator();
    Opcode opcode_cb_0xc2_generator();
    Opcode opcode_cb_0xc3_generator();
    Opcode opcode_cb_0xc4_generator();
    Opcode opcode_cb_0xc5_generator();
    Opcode opcode_cb_0xc6_generator();
    Opcode opcode_cb_0xc7_generator();
    Opcode opcode_cb_0xc8_generator();
    Opcode opcode_cb_0xc9_generator();
    Opcode opcode_cb_0xca_generator();
    Opcode opcode_cb_0xcb_generator();
    Opcode opcode_cb_0xcc_generator();
    Opcode opcode_cb_0xcd_generator();
    Opcode opcode_cb_0xce_generator();
    Opcode opcode_cb_0xcf_generator();
    Opcode opcode_cb_0xd0_generator();
    Opcode opcode_cb_0xd1_generator();
    Opcode opcode_cb_0xd2_generator();
    Opcode opcode_cb_0xd3_generator();
    Opcode opcode_cb_0xd4_generator();
    Opcode opcode_cb_0xd5_generator();
    Opcode opcode_cb_0xd6_generator();
    Opcode opcode_cb_0xd7_generator();
    Opcode opcode_cb_0xd8_generator();
    Opcode opcode_cb_0xd9_generator();
    Opcode opcode_cb_0xda_generator();
    Opcode opcode_cb_0xdb_generator();
    Opcode opcode_cb_0xdc_generator();
    Opcode opcode_cb_0xdd_generator();
    Opcode opcode_cb_0xde_generator();
    Opcode opcode_cb_0xdf_generator();
    Opcode opcode_cb_0xe0_generator();
    Opcode opcode_cb_0xe1_generator();
    Opcode opcode_cb_0xe2_generator();
    Opcode opcode_cb_0xe3_generator();
    Opcode opcode_cb_0xe4_generator();
    Opcode opcode_cb_0xe5_generator();
    Opcode opcode_cb_0xe6_generator();
    Opcode opcode_cb_0xe7_generator();
    Opcode opcode_cb_0xe8_generator();
    Opcode opcode_cb_0xe9_generator();
    Opcode opcode_cb_0xea_generator();
    Opcode opcode_cb_0xeb_generator();
    Opcode opcode_cb_0xec_generator();
    Opcode opcode_cb_0xed_generator();
    Opcode opcode_cb_0xee_generator();
    Opcode opcode_cb_0xef_generator();
    Opcode opcode_cb_0xf0_generator();
    Opcode opcode_cb_0xf1_generator();
    Opcode opcode_cb_0xf2_generator();
    Opcode opcode_cb_0xf3_generator();
    Opcode opcode_cb_0xf4_generator();
    Opcode opcode_cb_0xf5_generator();
    Opcode opcode_cb_0xf6_generator();
    Opcode opcode_cb_0xf7_generator();
    Opcode opcode_cb_0xf8_generator();
    Opcode opcode_cb_0xf9_generator();
    Opcode opcode_cb_0xfa_generator();
    Opcode opcode_cb_0xfb_generator();
    Opcode opcode_cb_0xfc_generator();
    Opcode opcode_cb_0xfd_generator();
    Opcode opcode_cb_0xfe_generator();
    Opcode opcode_cb_0xff_generator();

    // Opcode variables
    Opcode opcode_0x00 = opcode_0x00_generator();
    Opcode opcode_0x01 = opcode_0x01_generator();
    Opcode opcode_0x02 = opcode_0x02_generator();
    Opcode opcode_0x03 = opcode_0x03_generator();
    Opcode opcode_0x04 = opcode_0x04_generator();
    Opcode opcode_0x05 = opcode_0x05_generator();
    Opcode opcode_0x06 = opcode_0x06_generator();
    Opcode opcode_0x07 = opcode_0x07_generator();
    Opcode opcode_0x08 = opcode_0x08_generator();
    Opcode opcode_0x09 = opcode_0x09_generator();
    Opcode opcode_0x0a = opcode_0x0a_generator();
    Opcode opcode_0x0b = opcode_0x0b_generator();
    Opcode opcode_0x0c = opcode_0x0c_generator();
    Opcode opcode_0x0d = opcode_0x0d_generator();
    Opcode opcode_0x0e = opcode_0x0e_generator();
    Opcode opcode_0x0f = opcode_0x0f_generator();
    Opcode opcode_0x10 = opcode_0x10_generator();
    Opcode opcode_0x11 = opcode_0x11_generator();
    Opcode opcode_0x12 = opcode_0x12_generator();
    Opcode opcode_0x13 = opcode_0x13_generator();
    Opcode opcode_0x14 = opcode_0x14_generator();
    Opcode opcode_0x15 = opcode_0x15_generator();
    Opcode opcode_0x16 = opcode_0x16_generator();
    Opcode opcode_0x17 = opcode_0x17_generator();
    Opcode opcode_0x18 = opcode_0x18_generator();
    Opcode opcode_0x19 = opcode_0x19_generator();
    Opcode opcode_0x1a = opcode_0x1a_generator();
    Opcode opcode_0x1b = opcode_0x1b_generator();
    Opcode opcode_0x1c = opcode_0x1c_generator();
    Opcode opcode_0x1d = opcode_0x1d_generator();
    Opcode opcode_0x1e = opcode_0x1e_generator();
    Opcode opcode_0x1f = opcode_0x1f_generator();
    Opcode opcode_0x20 = opcode_0x20_generator();
    Opcode opcode_0x21 = opcode_0x21_generator();
    Opcode opcode_0x22 = opcode_0x22_generator();
    Opcode opcode_0x23 = opcode_0x23_generator();
    Opcode opcode_0x24 = opcode_0x24_generator();
    Opcode opcode_0x25 = opcode_0x25_generator();
    Opcode opcode_0x26 = opcode_0x26_generator();
    Opcode opcode_0x27 = opcode_0x27_generator();
    Opcode opcode_0x28 = opcode_0x28_generator();
    Opcode opcode_0x29 = opcode_0x29_generator();
    Opcode opcode_0x2a = opcode_0x2a_generator();
    Opcode opcode_0x2b = opcode_0x2b_generator();
    Opcode opcode_0x2c = opcode_0x2c_generator();
    Opcode opcode_0x2d = opcode_0x2d_generator();
    Opcode opcode_0x2e = opcode_0x2e_generator();
    Opcode opcode_0x2f = opcode_0x2f_generator();
    Opcode opcode_0x30 = opcode_0x30_generator();
    Opcode opcode_0x31 = opcode_0x31_generator();
    Opcode opcode_0x32 = opcode_0x32_generator();
    Opcode opcode_0x33 = opcode_0x33_generator();
    Opcode opcode_0x34 = opcode_0x34_generator();
    Opcode opcode_0x35 = opcode_0x35_generator();
    Opcode opcode_0x36 = opcode_0x36_generator();
    Opcode opcode_0x37 = opcode_0x37_generator();
    Opcode opcode_0x38 = opcode_0x38_generator();
    Opcode opcode_0x39 = opcode_0x39_generator();
    Opcode opcode_0x3a = opcode_0x3a_generator();
    Opcode opcode_0x3b = opcode_0x3b_generator();
    Opcode opcode_0x3c = opcode_0x3c_generator();
    Opcode opcode_0x3d = opcode_0x3d_generator();
    Opcode opcode_0x3e = opcode_0x3e_generator();
    Opcode opcode_0x3f = opcode_0x3f_generator();
    Opcode opcode_0x40 = opcode_0x40_generator();
    Opcode opcode_0x41 = opcode_0x41_generator();
    Opcode opcode_0x42 = opcode_0x42_generator();
    Opcode opcode_0x43 = opcode_0x43_generator();
    Opcode opcode_0x44 = opcode_0x44_generator();
    Opcode opcode_0x45 = opcode_0x45_generator();
    Opcode opcode_0x46 = opcode_0x46_generator();
    Opcode opcode_0x47 = opcode_0x47_generator();
    Opcode opcode_0x48 = opcode_0x48_generator();
    Opcode opcode_0x49 = opcode_0x49_generator();
    Opcode opcode_0x4a = opcode_0x4a_generator();
    Opcode opcode_0x4b = opcode_0x4b_generator();
    Opcode opcode_0x4c = opcode_0x4c_generator();
    Opcode opcode_0x4d = opcode_0x4d_generator();
    Opcode opcode_0x4e = opcode_0x4e_generator();
    Opcode opcode_0x4f = opcode_0x4f_generator();
    Opcode opcode_0x50 = opcode_0x50_generator();
    Opcode opcode_0x51 = opcode_0x51_generator();
    Opcode opcode_0x52 = opcode_0x52_generator();
    Opcode opcode_0x53 = opcode_0x53_generator();
    Opcode opcode_0x54 = opcode_0x54_generator();
    Opcode opcode_0x55 = opcode_0x55_generator();
    Opcode opcode_0x56 = opcode_0x56_generator();
    Opcode opcode_0x57 = opcode_0x57_generator();
    Opcode opcode_0x58 = opcode_0x58_generator();
    Opcode opcode_0x59 = opcode_0x59_generator();
    Opcode opcode_0x5a = opcode_0x5a_generator();
    Opcode opcode_0x5b = opcode_0x5b_generator();
    Opcode opcode_0x5c = opcode_0x5c_generator();
    Opcode opcode_0x5d = opcode_0x5d_generator();
    Opcode opcode_0x5e = opcode_0x5e_generator();
    Opcode opcode_0x5f = opcode_0x5f_generator();
    Opcode opcode_0x60 = opcode_0x60_generator();
    Opcode opcode_0x61 = opcode_0x61_generator();
    Opcode opcode_0x62 = opcode_0x62_generator();
    Opcode opcode_0x63 = opcode_0x63_generator();
    Opcode opcode_0x64 = opcode_0x64_generator();
    Opcode opcode_0x65 = opcode_0x65_generator();
    Opcode opcode_0x66 = opcode_0x66_generator();
    Opcode opcode_0x67 = opcode_0x67_generator();
    Opcode opcode_0x68 = opcode_0x68_generator();
    Opcode opcode_0x69 = opcode_0x69_generator();
    Opcode opcode_0x6a = opcode_0x6a_generator();
    Opcode opcode_0x6b = opcode_0x6b_generator();
    Opcode opcode_0x6c = opcode_0x6c_generator();
    Opcode opcode_0x6d = opcode_0x6d_generator();
    Opcode opcode_0x6e = opcode_0x6e_generator();
    Opcode opcode_0x6f = opcode_0x6f_generator();
    Opcode opcode_0x70 = opcode_0x70_generator();
    Opcode opcode_0x71 = opcode_0x71_generator();
    Opcode opcode_0x72 = opcode_0x72_generator();
    Opcode opcode_0x73 = opcode_0x73_generator();
    Opcode opcode_0x74 = opcode_0x74_generator();
    Opcode opcode_0x75 = opcode_0x75_generator();
    Opcode opcode_0x76 = opcode_0x76_generator();
    Opcode opcode_0x77 = opcode_0x77_generator();
    Opcode opcode_0x78 = opcode_0x78_generator();
    Opcode opcode_0x79 = opcode_0x79_generator();
    Opcode opcode_0x7a = opcode_0x7a_generator();
    Opcode opcode_0x7b = opcode_0x7b_generator();
    Opcode opcode_0x7c = opcode_0x7c_generator();
    Opcode opcode_0x7d = opcode_0x7d_generator();
    Opcode opcode_0x7e = opcode_0x7e_generator();
    Opcode opcode_0x7f = opcode_0x7f_generator();
    Opcode opcode_0x80 = opcode_0x80_generator();
    Opcode opcode_0x81 = opcode_0x81_generator();
    Opcode opcode_0x82 = opcode_0x82_generator();
    Opcode opcode_0x83 = opcode_0x83_generator();
    Opcode opcode_0x84 = opcode_0x84_generator();
    Opcode opcode_0x85 = opcode_0x85_generator();
    Opcode opcode_0x86 = opcode_0x86_generator();
    Opcode opcode_0x87 = opcode_0x87_generator();
    Opcode opcode_0x88 = opcode_0x88_generator();
    Opcode opcode_0x89 = opcode_0x89_generator();
    Opcode opcode_0x8a = opcode_0x8a_generator();
    Opcode opcode_0x8b = opcode_0x8b_generator();
    Opcode opcode_0x8c = opcode_0x8c_generator();
    Opcode opcode_0x8d = opcode_0x8d_generator();
    Opcode opcode_0x8e = opcode_0x8e_generator();
    Opcode opcode_0x8f = opcode_0x8f_generator();
    Opcode opcode_0x90 = opcode_0x90_generator();
    Opcode opcode_0x91 = opcode_0x91_generator();
    Opcode opcode_0x92 = opcode_0x92_generator();
    Opcode opcode_0x93 = opcode_0x93_generator();
    Opcode opcode_0x94 = opcode_0x94_generator();
    Opcode opcode_0x95 = opcode_0x95_generator();
    Opcode opcode_0x96 = opcode_0x96_generator();
    Opcode opcode_0x97 = opcode_0x97_generator();
    Opcode opcode_0x98 = opcode_0x98_generator();
    Opcode opcode_0x99 = opcode_0x99_generator();
    Opcode opcode_0x9a = opcode_0x9a_generator();
    Opcode opcode_0x9b = opcode_0x9b_generator();
    Opcode opcode_0x9c = opcode_0x9c_generator();
    Opcode opcode_0x9d = opcode_0x9d_generator();
    Opcode opcode_0x9e = opcode_0x9e_generator();
    Opcode opcode_0x9f = opcode_0x9f_generator();
    Opcode opcode_0xa0 = opcode_0xa0_generator();
    Opcode opcode_0xa1 = opcode_0xa1_generator();
    Opcode opcode_0xa2 = opcode_0xa2_generator();
    Opcode opcode_0xa3 = opcode_0xa3_generator();
    Opcode opcode_0xa4 = opcode_0xa4_generator();
    Opcode opcode_0xa5 = opcode_0xa5_generator();
    Opcode opcode_0xa6 = opcode_0xa6_generator();
    Opcode opcode_0xa7 = opcode_0xa7_generator();
    Opcode opcode_0xa8 = opcode_0xa8_generator();
    Opcode opcode_0xa9 = opcode_0xa9_generator();
    Opcode opcode_0xaa = opcode_0xaa_generator();
    Opcode opcode_0xab = opcode_0xab_generator();
    Opcode opcode_0xac = opcode_0xac_generator();
    Opcode opcode_0xad = opcode_0xad_generator();
    Opcode opcode_0xae = opcode_0xae_generator();
    Opcode opcode_0xaf = opcode_0xaf_generator();
    Opcode opcode_0xb0 = opcode_0xb0_generator();
    Opcode opcode_0xb1 = opcode_0xb1_generator();
    Opcode opcode_0xb2 = opcode_0xb2_generator();
    Opcode opcode_0xb3 = opcode_0xb3_generator();
    Opcode opcode_0xb4 = opcode_0xb4_generator();
    Opcode opcode_0xb5 = opcode_0xb5_generator();
    Opcode opcode_0xb6 = opcode_0xb6_generator();
    Opcode opcode_0xb7 = opcode_0xb7_generator();
    Opcode opcode_0xb8 = opcode_0xb8_generator();
    Opcode opcode_0xb9 = opcode_0xb9_generator();
    Opcode opcode_0xba = opcode_0xba_generator();
    Opcode opcode_0xbb = opcode_0xbb_generator();
    Opcode opcode_0xbc = opcode_0xbc_generator();
    Opcode opcode_0xbd = opcode_0xbd_generator();
    Opcode opcode_0xbe = opcode_0xbe_generator();
    Opcode opcode_0xbf = opcode_0xbf_generator();
    Opcode opcode_0xc0 = opcode_0xc0_generator();
    Opcode opcode_0xc1 = opcode_0xc1_generator();
    Opcode opcode_0xc2 = opcode_0xc2_generator();
    Opcode opcode_0xc3 = opcode_0xc3_generator();
    Opcode opcode_0xc4 = opcode_0xc4_generator();
    Opcode opcode_0xc5 = opcode_0xc5_generator();
    Opcode opcode_0xc6 = opcode_0xc6_generator();
    Opcode opcode_0xc7 = opcode_0xc7_generator();
    Opcode opcode_0xc8 = opcode_0xc8_generator();
    Opcode opcode_0xc9 = opcode_0xc9_generator();
    Opcode opcode_0xca = opcode_0xca_generator();
    Opcode opcode_0xcb = opcode_0xcb_generator();
    Opcode opcode_0xcc = opcode_0xcc_generator();
    Opcode opcode_0xcd = opcode_0xcd_generator();
    Opcode opcode_0xce = opcode_0xce_generator();
    Opcode opcode_0xcf = opcode_0xcf_generator();
    Opcode opcode_0xd0 = opcode_0xd0_generator();
    Opcode opcode_0xd1 = opcode_0xd1_generator();
    Opcode opcode_0xd2 = opcode_0xd2_generator();
    Opcode opcode_0xd4 = opcode_0xd4_generator();
    Opcode opcode_0xd5 = opcode_0xd5_generator();
    Opcode opcode_0xd6 = opcode_0xd6_generator();
    Opcode opcode_0xd7 = opcode_0xd7_generator();
    Opcode opcode_0xd8 = opcode_0xd8_generator();
    Opcode opcode_0xd9 = opcode_0xd9_generator();
    Opcode opcode_0xda = opcode_0xda_generator();
    Opcode opcode_0xdc = opcode_0xdc_generator();
    Opcode opcode_0xde = opcode_0xde_generator();
    Opcode opcode_0xdf = opcode_0xdf_generator();
    Opcode opcode_0xe0 = opcode_0xe0_generator();
    Opcode opcode_0xe1 = opcode_0xe1_generator();
    Opcode opcode_0xe2 = opcode_0xe2_generator();
    Opcode opcode_0xe5 = opcode_0xe5_generator();
    Opcode opcode_0xe6 = opcode_0xe6_generator();
    Opcode opcode_0xe7 = opcode_0xe7_generator();
    Opcode opcode_0xe8 = opcode_0xe8_generator();
    Opcode opcode_0xe9 = opcode_0xe9_generator();
    Opcode opcode_0xea = opcode_0xea_generator();
    Opcode opcode_0xee = opcode_0xee_generator();
    Opcode opcode_0xef = opcode_0xef_generator();
    Opcode opcode_0xf0 = opcode_0xf0_generator();
    Opcode opcode_0xf1 = opcode_0xf1_generator();
    Opcode opcode_0xf2 = opcode_0xf2_generator();
    Opcode opcode_0xf3 = opcode_0xf3_generator();
    Opcode opcode_0xf5 = opcode_0xf5_generator();
    Opcode opcode_0xf6 = opcode_0xf6_generator();
    Opcode opcode_0xf7 = opcode_0xf7_generator();
    Opcode opcode_0xf8 = opcode_0xf8_generator();
    Opcode opcode_0xf9 = opcode_0xf9_generator();
    Opcode opcode_0xfa = opcode_0xfa_generator();
    Opcode opcode_0xfb = opcode_0xfb_generator();
    Opcode opcode_0xfe = opcode_0xfe_generator();
    Opcode opcode_0xff = opcode_0xff_generator();

    // CB opcode variables
    Opcode opcode_cb_0x00 = opcode_cb_0x00_generator();
    Opcode opcode_cb_0x01 = opcode_cb_0x01_generator();
    Opcode opcode_cb_0x02 = opcode_cb_0x02_generator();
    Opcode opcode_cb_0x03 = opcode_cb_0x03_generator();
    Opcode opcode_cb_0x04 = opcode_cb_0x04_generator();
    Opcode opcode_cb_0x05 = opcode_cb_0x05_generator();
    Opcode opcode_cb_0x06 = opcode_cb_0x06_generator();
    Opcode opcode_cb_0x07 = opcode_cb_0x07_generator();
    Opcode opcode_cb_0x08 = opcode_cb_0x08_generator();
    Opcode opcode_cb_0x09 = opcode_cb_0x09_generator();
    Opcode opcode_cb_0x0a = opcode_cb_0x0a_generator();
    Opcode opcode_cb_0x0b = opcode_cb_0x0b_generator();
    Opcode opcode_cb_0x0c = opcode_cb_0x0c_generator();
    Opcode opcode_cb_0x0d = opcode_cb_0x0d_generator();
    Opcode opcode_cb_0x0e = opcode_cb_0x0e_generator();
    Opcode opcode_cb_0x0f = opcode_cb_0x0f_generator();
    Opcode opcode_cb_0x10 = opcode_cb_0x10_generator();
    Opcode opcode_cb_0x11 = opcode_cb_0x11_generator();
    Opcode opcode_cb_0x12 = opcode_cb_0x12_generator();
    Opcode opcode_cb_0x13 = opcode_cb_0x13_generator();
    Opcode opcode_cb_0x14 = opcode_cb_0x14_generator();
    Opcode opcode_cb_0x15 = opcode_cb_0x15_generator();
    Opcode opcode_cb_0x16 = opcode_cb_0x16_generator();
    Opcode opcode_cb_0x17 = opcode_cb_0x17_generator();
    Opcode opcode_cb_0x18 = opcode_cb_0x18_generator();
    Opcode opcode_cb_0x19 = opcode_cb_0x19_generator();
    Opcode opcode_cb_0x1a = opcode_cb_0x1a_generator();
    Opcode opcode_cb_0x1b = opcode_cb_0x1b_generator();
    Opcode opcode_cb_0x1c = opcode_cb_0x1c_generator();
    Opcode opcode_cb_0x1d = opcode_cb_0x1d_generator();
    Opcode opcode_cb_0x1e = opcode_cb_0x1e_generator();
    Opcode opcode_cb_0x1f = opcode_cb_0x1f_generator();
    Opcode opcode_cb_0x20 = opcode_cb_0x20_generator();
    Opcode opcode_cb_0x21 = opcode_cb_0x21_generator();
    Opcode opcode_cb_0x22 = opcode_cb_0x22_generator();
    Opcode opcode_cb_0x23 = opcode_cb_0x23_generator();
    Opcode opcode_cb_0x24 = opcode_cb_0x24_generator();
    Opcode opcode_cb_0x25 = opcode_cb_0x25_generator();
    Opcode opcode_cb_0x26 = opcode_cb_0x26_generator();
    Opcode opcode_cb_0x27 = opcode_cb_0x27_generator();
    Opcode opcode_cb_0x28 = opcode_cb_0x28_generator();
    Opcode opcode_cb_0x29 = opcode_cb_0x29_generator();
    Opcode opcode_cb_0x2a = opcode_cb_0x2a_generator();
    Opcode opcode_cb_0x2b = opcode_cb_0x2b_generator();
    Opcode opcode_cb_0x2c = opcode_cb_0x2c_generator();
    Opcode opcode_cb_0x2d = opcode_cb_0x2d_generator();
    Opcode opcode_cb_0x2e = opcode_cb_0x2e_generator();
    Opcode opcode_cb_0x2f = opcode_cb_0x2f_generator();
    Opcode opcode_cb_0x30 = opcode_cb_0x30_generator();
    Opcode opcode_cb_0x31 = opcode_cb_0x31_generator();
    Opcode opcode_cb_0x32 = opcode_cb_0x32_generator();
    Opcode opcode_cb_0x33 = opcode_cb_0x33_generator();
    Opcode opcode_cb_0x34 = opcode_cb_0x34_generator();
    Opcode opcode_cb_0x35 = opcode_cb_0x35_generator();
    Opcode opcode_cb_0x36 = opcode_cb_0x36_generator();
    Opcode opcode_cb_0x37 = opcode_cb_0x37_generator();
    Opcode opcode_cb_0x38 = opcode_cb_0x38_generator();
    Opcode opcode_cb_0x39 = opcode_cb_0x39_generator();
    Opcode opcode_cb_0x3a = opcode_cb_0x3a_generator();
    Opcode opcode_cb_0x3b = opcode_cb_0x3b_generator();
    Opcode opcode_cb_0x3c = opcode_cb_0x3c_generator();
    Opcode opcode_cb_0x3d = opcode_cb_0x3d_generator();
    Opcode opcode_cb_0x3e = opcode_cb_0x3e_generator();
    Opcode opcode_cb_0x3f = opcode_cb_0x3f_generator();
    Opcode opcode_cb_0x40 = opcode_cb_0x40_generator();
    Opcode opcode_cb_0x41 = opcode_cb_0x41_generator();
    Opcode opcode_cb_0x42 = opcode_cb_0x42_generator();
    Opcode opcode_cb_0x43 = opcode_cb_0x43_generator();
    Opcode opcode_cb_0x44 = opcode_cb_0x44_generator();
    Opcode opcode_cb_0x45 = opcode_cb_0x45_generator();
    Opcode opcode_cb_0x46 = opcode_cb_0x46_generator();
    Opcode opcode_cb_0x47 = opcode_cb_0x47_generator();
    Opcode opcode_cb_0x48 = opcode_cb_0x48_generator();
    Opcode opcode_cb_0x49 = opcode_cb_0x49_generator();
    Opcode opcode_cb_0x4a = opcode_cb_0x4a_generator();
    Opcode opcode_cb_0x4b = opcode_cb_0x4b_generator();
    Opcode opcode_cb_0x4c = opcode_cb_0x4c_generator();
    Opcode opcode_cb_0x4d = opcode_cb_0x4d_generator();
    Opcode opcode_cb_0x4e = opcode_cb_0x4e_generator();
    Opcode opcode_cb_0x4f = opcode_cb_0x4f_generator();
    Opcode opcode_cb_0x50 = opcode_cb_0x50_generator();
    Opcode opcode_cb_0x51 = opcode_cb_0x51_generator();
    Opcode opcode_cb_0x52 = opcode_cb_0x52_generator();
    Opcode opcode_cb_0x53 = opcode_cb_0x53_generator();
    Opcode opcode_cb_0x54 = opcode_cb_0x54_generator();
    Opcode opcode_cb_0x55 = opcode_cb_0x55_generator();
    Opcode opcode_cb_0x56 = opcode_cb_0x56_generator();
    Opcode opcode_cb_0x57 = opcode_cb_0x57_generator();
    Opcode opcode_cb_0x58 = opcode_cb_0x58_generator();
    Opcode opcode_cb_0x59 = opcode_cb_0x59_generator();
    Opcode opcode_cb_0x5a = opcode_cb_0x5a_generator();
    Opcode opcode_cb_0x5b = opcode_cb_0x5b_generator();
    Opcode opcode_cb_0x5c = opcode_cb_0x5c_generator();
    Opcode opcode_cb_0x5d = opcode_cb_0x5d_generator();
    Opcode opcode_cb_0x5e = opcode_cb_0x5e_generator();
    Opcode opcode_cb_0x5f = opcode_cb_0x5f_generator();
    Opcode opcode_cb_0x60 = opcode_cb_0x60_generator();
    Opcode opcode_cb_0x61 = opcode_cb_0x61_generator();
    Opcode opcode_cb_0x62 = opcode_cb_0x62_generator();
    Opcode opcode_cb_0x63 = opcode_cb_0x63_generator();
    Opcode opcode_cb_0x64 = opcode_cb_0x64_generator();
    Opcode opcode_cb_0x65 = opcode_cb_0x65_generator();
    Opcode opcode_cb_0x66 = opcode_cb_0x66_generator();
    Opcode opcode_cb_0x67 = opcode_cb_0x67_generator();
    Opcode opcode_cb_0x68 = opcode_cb_0x68_generator();
    Opcode opcode_cb_0x69 = opcode_cb_0x69_generator();
    Opcode opcode_cb_0x6a = opcode_cb_0x6a_generator();
    Opcode opcode_cb_0x6b = opcode_cb_0x6b_generator();
    Opcode opcode_cb_0x6c = opcode_cb_0x6c_generator();
    Opcode opcode_cb_0x6d = opcode_cb_0x6d_generator();
    Opcode opcode_cb_0x6e = opcode_cb_0x6e_generator();
    Opcode opcode_cb_0x6f = opcode_cb_0x6f_generator();
    Opcode opcode_cb_0x70 = opcode_cb_0x70_generator();
    Opcode opcode_cb_0x71 = opcode_cb_0x71_generator();
    Opcode opcode_cb_0x72 = opcode_cb_0x72_generator();
    Opcode opcode_cb_0x73 = opcode_cb_0x73_generator();
    Opcode opcode_cb_0x74 = opcode_cb_0x74_generator();
    Opcode opcode_cb_0x75 = opcode_cb_0x75_generator();
    Opcode opcode_cb_0x76 = opcode_cb_0x76_generator();
    Opcode opcode_cb_0x77 = opcode_cb_0x77_generator();
    Opcode opcode_cb_0x78 = opcode_cb_0x78_generator();
    Opcode opcode_cb_0x79 = opcode_cb_0x79_generator();
    Opcode opcode_cb_0x7a = opcode_cb_0x7a_generator();
    Opcode opcode_cb_0x7b = opcode_cb_0x7b_generator();
    Opcode opcode_cb_0x7c = opcode_cb_0x7c_generator();
    Opcode opcode_cb_0x7d = opcode_cb_0x7d_generator();
    Opcode opcode_cb_0x7e = opcode_cb_0x7e_generator();
    Opcode opcode_cb_0x7f = opcode_cb_0x7f_generator();
    Opcode opcode_cb_0x80 = opcode_cb_0x80_generator();
    Opcode opcode_cb_0x81 = opcode_cb_0x81_generator();
    Opcode opcode_cb_0x82 = opcode_cb_0x82_generator();
    Opcode opcode_cb_0x83 = opcode_cb_0x83_generator();
    Opcode opcode_cb_0x84 = opcode_cb_0x84_generator();
    Opcode opcode_cb_0x85 = opcode_cb_0x85_generator();
    Opcode opcode_cb_0x86 = opcode_cb_0x86_generator();
    Opcode opcode_cb_0x87 = opcode_cb_0x87_generator();
    Opcode opcode_cb_0x88 = opcode_cb_0x88_generator();
    Opcode opcode_cb_0x89 = opcode_cb_0x89_generator();
    Opcode opcode_cb_0x8a = opcode_cb_0x8a_generator();
    Opcode opcode_cb_0x8b = opcode_cb_0x8b_generator();
    Opcode opcode_cb_0x8c = opcode_cb_0x8c_generator();
    Opcode opcode_cb_0x8d = opcode_cb_0x8d_generator();
    Opcode opcode_cb_0x8e = opcode_cb_0x8e_generator();
    Opcode opcode_cb_0x8f = opcode_cb_0x8f_generator();
    Opcode opcode_cb_0x90 = opcode_cb_0x90_generator();
    Opcode opcode_cb_0x91 = opcode_cb_0x91_generator();
    Opcode opcode_cb_0x92 = opcode_cb_0x92_generator();
    Opcode opcode_cb_0x93 = opcode_cb_0x93_generator();
    Opcode opcode_cb_0x94 = opcode_cb_0x94_generator();
    Opcode opcode_cb_0x95 = opcode_cb_0x95_generator();
    Opcode opcode_cb_0x96 = opcode_cb_0x96_generator();
    Opcode opcode_cb_0x97 = opcode_cb_0x97_generator();
    Opcode opcode_cb_0x98 = opcode_cb_0x98_generator();
    Opcode opcode_cb_0x99 = opcode_cb_0x99_generator();
    Opcode opcode_cb_0x9a = opcode_cb_0x9a_generator();
    Opcode opcode_cb_0x9b = opcode_cb_0x9b_generator();
    Opcode opcode_cb_0x9c = opcode_cb_0x9c_generator();
    Opcode opcode_cb_0x9d = opcode_cb_0x9d_generator();
    Opcode opcode_cb_0x9e = opcode_cb_0x9e_generator();
    Opcode opcode_cb_0x9f = opcode_cb_0x9f_generator();
    Opcode opcode_cb_0xa0 = opcode_cb_0xa0_generator();
    Opcode opcode_cb_0xa1 = opcode_cb_0xa1_generator();
    Opcode opcode_cb_0xa2 = opcode_cb_0xa2_generator();
    Opcode opcode_cb_0xa3 = opcode_cb_0xa3_generator();
    Opcode opcode_cb_0xa4 = opcode_cb_0xa4_generator();
    Opcode opcode_cb_0xa5 = opcode_cb_0xa5_generator();
    Opcode opcode_cb_0xa6 = opcode_cb_0xa6_generator();
    Opcode opcode_cb_0xa7 = opcode_cb_0xa7_generator();
    Opcode opcode_cb_0xa8 = opcode_cb_0xa8_generator();
    Opcode opcode_cb_0xa9 = opcode_cb_0xa9_generator();
    Opcode opcode_cb_0xaa = opcode_cb_0xaa_generator();
    Opcode opcode_cb_0xab = opcode_cb_0xab_generator();
    Opcode opcode_cb_0xac = opcode_cb_0xac_generator();
    Opcode opcode_cb_0xad = opcode_cb_0xad_generator();
    Opcode opcode_cb_0xae = opcode_cb_0xae_generator();
    Opcode opcode_cb_0xaf = opcode_cb_0xaf_generator();
    Opcode opcode_cb_0xb0 = opcode_cb_0xb0_generator();
    Opcode opcode_cb_0xb1 = opcode_cb_0xb1_generator();
    Opcode opcode_cb_0xb2 = opcode_cb_0xb2_generator();
    Opcode opcode_cb_0xb3 = opcode_cb_0xb3_generator();
    Opcode opcode_cb_0xb4 = opcode_cb_0xb4_generator();
    Opcode opcode_cb_0xb5 = opcode_cb_0xb5_generator();
    Opcode opcode_cb_0xb6 = opcode_cb_0xb6_generator();
    Opcode opcode_cb_0xb7 = opcode_cb_0xb7_generator();
    Opcode opcode_cb_0xb8 = opcode_cb_0xb8_generator();
    Opcode opcode_cb_0xb9 = opcode_cb_0xb9_generator();
    Opcode opcode_cb_0xba = opcode_cb_0xba_generator();
    Opcode opcode_cb_0xbb = opcode_cb_0xbb_generator();
    Opcode opcode_cb_0xbc = opcode_cb_0xbc_generator();
    Opcode opcode_cb_0xbd = opcode_cb_0xbd_generator();
    Opcode opcode_cb_0xbe = opcode_cb_0xbe_generator();
    Opcode opcode_cb_0xbf = opcode_cb_0xbf_generator();
    Opcode opcode_cb_0xc0 = opcode_cb_0xc0_generator();
    Opcode opcode_cb_0xc1 = opcode_cb_0xc1_generator();
    Opcode opcode_cb_0xc2 = opcode_cb_0xc2_generator();
    Opcode opcode_cb_0xc3 = opcode_cb_0xc3_generator();
    Opcode opcode_cb_0xc4 = opcode_cb_0xc4_generator();
    Opcode opcode_cb_0xc5 = opcode_cb_0xc5_generator();
    Opcode opcode_cb_0xc6 = opcode_cb_0xc6_generator();
    Opcode opcode_cb_0xc7 = opcode_cb_0xc7_generator();
    Opcode opcode_cb_0xc8 = opcode_cb_0xc8_generator();
    Opcode opcode_cb_0xc9 = opcode_cb_0xc9_generator();
    Opcode opcode_cb_0xca = opcode_cb_0xca_generator();
    Opcode opcode_cb_0xcb = opcode_cb_0xcb_generator();
    Opcode opcode_cb_0xcc = opcode_cb_0xcc_generator();
    Opcode opcode_cb_0xcd = opcode_cb_0xcd_generator();
    Opcode opcode_cb_0xce = opcode_cb_0xce_generator();
    Opcode opcode_cb_0xcf = opcode_cb_0xcf_generator();
    Opcode opcode_cb_0xd0 = opcode_cb_0xd0_generator();
    Opcode opcode_cb_0xd1 = opcode_cb_0xd1_generator();
    Opcode opcode_cb_0xd2 = opcode_cb_0xd2_generator();
    Opcode opcode_cb_0xd3 = opcode_cb_0xd3_generator();
    Opcode opcode_cb_0xd4 = opcode_cb_0xd4_generator();
    Opcode opcode_cb_0xd5 = opcode_cb_0xd5_generator();
    Opcode opcode_cb_0xd6 = opcode_cb_0xd6_generator();
    Opcode opcode_cb_0xd7 = opcode_cb_0xd7_generator();
    Opcode opcode_cb_0xd8 = opcode_cb_0xd8_generator();
    Opcode opcode_cb_0xd9 = opcode_cb_0xd9_generator();
    Opcode opcode_cb_0xda = opcode_cb_0xda_generator();
    Opcode opcode_cb_0xdb = opcode_cb_0xdb_generator();
    Opcode opcode_cb_0xdc = opcode_cb_0xdc_generator();
    Opcode opcode_cb_0xdd = opcode_cb_0xdd_generator();
    Opcode opcode_cb_0xde = opcode_cb_0xde_generator();
    Opcode opcode_cb_0xdf = opcode_cb_0xdf_generator();
    Opcode opcode_cb_0xe0 = opcode_cb_0xe0_generator();
    Opcode opcode_cb_0xe1 = opcode_cb_0xe1_generator();
    Opcode opcode_cb_0xe2 = opcode_cb_0xe2_generator();
    Opcode opcode_cb_0xe3 = opcode_cb_0xe3_generator();
    Opcode opcode_cb_0xe4 = opcode_cb_0xe4_generator();
    Opcode opcode_cb_0xe5 = opcode_cb_0xe5_generator();
    Opcode opcode_cb_0xe6 = opcode_cb_0xe6_generator();
    Opcode opcode_cb_0xe7 = opcode_cb_0xe7_generator();
    Opcode opcode_cb_0xe8 = opcode_cb_0xe8_generator();
    Opcode opcode_cb_0xe9 = opcode_cb_0xe9_generator();
    Opcode opcode_cb_0xea = opcode_cb_0xea_generator();
    Opcode opcode_cb_0xeb = opcode_cb_0xeb_generator();
    Opcode opcode_cb_0xec = opcode_cb_0xec_generator();
    Opcode opcode_cb_0xed = opcode_cb_0xed_generator();
    Opcode opcode_cb_0xee = opcode_cb_0xee_generator();
    Opcode opcode_cb_0xef = opcode_cb_0xef_generator();
    Opcode opcode_cb_0xf0 = opcode_cb_0xf0_generator();
    Opcode opcode_cb_0xf1 = opcode_cb_0xf1_generator();
    Opcode opcode_cb_0xf2 = opcode_cb_0xf2_generator();
    Opcode opcode_cb_0xf3 = opcode_cb_0xf3_generator();
    Opcode opcode_cb_0xf4 = opcode_cb_0xf4_generator();
    Opcode opcode_cb_0xf5 = opcode_cb_0xf5_generator();
    Opcode opcode_cb_0xf6 = opcode_cb_0xf6_generator();
    Opcode opcode_cb_0xf7 = opcode_cb_0xf7_generator();
    Opcode opcode_cb_0xf8 = opcode_cb_0xf8_generator();
    Opcode opcode_cb_0xf9 = opcode_cb_0xf9_generator();
    Opcode opcode_cb_0xfa = opcode_cb_0xfa_generator();
    Opcode opcode_cb_0xfb = opcode_cb_0xfb_generator();
    Opcode opcode_cb_0xfc = opcode_cb_0xfc_generator();
    Opcode opcode_cb_0xfd = opcode_cb_0xfd_generator();
    Opcode opcode_cb_0xfe = opcode_cb_0xfe_generator();
    Opcode opcode_cb_0xff = opcode_cb_0xff_generator();

};

#endif